services:
  - docker

script:
  - >-
    docker build --build-arg BUILD_VERSION=${TRAVIS_BUILD_NUMBER}
    --build-arg COMMIT_SHA=$(git rev-parse HEAD) -t anz-test2 .
  - docker run -d -p 5000:5000 anz-test2
  - sleep 15
  - curl 127.0.0.1:5000/healthcheck | grep $(git rev-parse HEAD)